apply plugin: 'com.android.application'

android {
    namespace 'com.gemelodigital.esp32'
    compileSdk 35

    defaultConfig {
        applicationId 'com.gemelodigital.esp32'
        minSdk 23
        targetSdk 34
        versionCode 2
        versionName '1.1'
    }

    sourceSets {
        main.assets.srcDirs += file('../../data')
    }
}
