apply plugin: 'com.android.application'
apply plugin: 'org.jetbrains.kotlin.android'

android {
    namespace 'com.gemelodigital.esp32'
    compileSdk 35

    defaultConfig {
        applicationId 'com.gemelodigital.esp32'
        minSdk 24
        targetSdk 34
        versionCode 12
        versionName '1.11'
        testInstrumentationRunner 'com.gemelodigital.esp32.DashboardInstrumentation'
    }

    signingConfigs {
        debug {
            storeFile file('../.signing/debug.keystore')
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
        }
    }
    buildTypes {
        debug { signingConfig signingConfigs.debug }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions { jvmTarget = '1.8' }
}

dependencies {
    implementation 'androidx.activity:activity:1.9.3'
    implementation 'io.github.sceneview:sceneview:2.3.3'
    implementation 'org.iq80.leveldb:leveldb:0.9'
}

configurations.configureEach {
    exclude group: 'com.google.guava', module: 'listenablefuture'
}
